export {default as Bio} from './Bio'
export {default as Interests} from './Interests'
export {default as Location} from './Location'
export {default as TikTok} from './TikTok'
export {default as TikTokConfirm} from './TikTokConfirm'
export {default as Slider} from './Slider'
export {default as Header} from './Header'